name: CI

on:
  push:
    branches:
      - "master"
    tags:
      - "*"
  pull_request:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Cache vcpkg installed
        id: vcpkg-installed-cache
        uses: actions/cache@v1
        with:
          path: ${{ env.VCPKG_INSTALLATION_ROOT }}/installed
          key: ${{ hashFiles('**/vcpkg_*.txt') }}-${{ runner.os }}-vcpkg-installed
      - name: Cache vcpkg packages
        id: vcpkg-packages-cache
        uses: actions/cache@v1
        with:
          path: ${{ env.VCPKG_INSTALLATION_ROOT }}/packages
          key: ${{ hashFiles('**/vcpkg_*.txt') }}-${{ runner.os }}-vcpkg-packages
      - run: sudo apt-get update
        if: matrix.os == 'ubuntu-latest'
      - run: sudo apt-get install libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev
        if: matrix.os == 'ubuntu-latest'
      - run: echo "VCPKG_DEFAULT_TRIPLET=x64-windows" >> $env:GITHUB_ENV
        if: matrix.os == 'windows-latest'
      - run: echo "VCPKG_DEFAULT_TRIPLET=x64-linux" >> "$GITHUB_ENV"
        if: matrix.os == 'ubuntu-latest'
      - run: echo "VCPKG_DEFAULT_TRIPLET=x64-osx" >> "$GITHUB_ENV"
        if: matrix.os == 'macos-latest'
      - run: vcpkg install "@vcpkg_response_file.txt"
        if: steps.vcpkg-installed-cache.outputs.cache-hit != 'true' || steps.vcpkg-packages-cache.outputs.cache-hit != 'true'
        env: 
          VCPKG_DEFAULT_TRIPLET: ${{ env.VCPKG_DEFAULT_TRIPLET }}
      - run: cmake -DCMAKE_BUILD_TYPE=Release -Bbuild
      - run: cmake -DCMAKE_BUILD_TYPE=Release --build build
      - name: Package
        if: startsWith(github.ref, 'refs/tags')
        run: cmake -DCMAKE_BUILD_TYPE=Release --build build --target package
      - run: mv build/voxelscape.zip build/voxelscape-${{ env.VCPKG_DEFAULT_TRIPLET }}.zip
        if: startsWith(github.ref, 'refs/tags')
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/voxelscape-${{ env.VCPKG_DEFAULT_TRIPLET }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
