name: CI

on:
  push:
    branches: master
  pull_request:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev && sudo update-alternatives --set c++ /usr/bin/clang++-9
        if: matrix.os == 'ubuntu-latest'
      - run: echo "::set-env name=VCPKG_DEFAULT_TRIPLET::x64-windows"
        if: matrix.os == 'windows-latest'
      - run: vcpkg install glad glfw3 glm entt imgui
      - run: cmake -Bbuild
      - run: cmake  --build build